name: CI checks

on:
  push:
    # branches:
    #   - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1.8.32

      - name: Run CI checks
        run: pnpm ci-check
